version: "3.8"
services:
  analytics:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MODE: ${MODE:-jupyterlab}
    ports:
      - 127.0.0.1:8888:8888 # jupyterlab
    volumes:
      - ./:/app