version: "3.8"
services:
  jupyterlab:
    build:
      context: .
      dockerfile: Dockerfile        
    container_name: analytics
    environment:
      MODE: ${MODE:-dev}
      JUPYTER_LAB_PASSWORD: jlpasswd
    #restart: always
    ports:
      - 8888:8888 # jupyterlab
    volumes:
      - ./:/app