#!/bin/bash
## This script for updating requirements.txt using pip-compile
## prior running, manually write desired requirement to requirements.in files

# DEV-REQUIREMENTS (dev-requirements.in) is reserved for development environment requirements

# Requirements.txt generation
echo "Generating new requirements.txt... please wait."
pip-compile --upgrade --generate-hashes --allow-unsafe --resolver=backtracking -o requirements.txt requirements.in dev-requirements.in || (echo "Pip compile failed. This might happen due low memory. Please check requirements.in and dev-requirements.in files. " && exit 1)

# Add warning and info to newly generated file.
HEADER=$(cat <<-END
##################################################################################################################
#
# Note: Do not edit this file directly. Use requirements.in instead. See also update_requirements.sh.
#
# Step-by-step guide to update requirements:
#
# 1. Add your requirement to requirements.in
# 2. Run update_requirements.sh
# 3. Install requirements: pip install -r requirements.txt
#
##################################################################################################################
END
)

# Add header to requirements.txt
echo -e $HEADER | cat - requirements.txt > temp && mv temp requirements.txt

echo "New requirements.txt generated. You may install requirements to your environment by: pip install -r requirements.txt"