# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/analytics_template',
                'doc_host': 'https://Datahel.github.io',
                'git_url': 'https://github.com/Datahel/analytics_template',
                'lib_path': 'analytics_template'},
  'syms': {'analytics_template.core': {'analytics_template.core.foo': ('core.html#foo', 'analytics_template/core.py')}}}
