# This action.yml runs local dockerfile in test mode
name: 'Run analytics container'
description: 'Run repository tests in container using local dockerfile'
runs:
  using: 'docker'
  image: '../../../Dockerfile'