on: [push]

jobs:
  ci_test_job:
    runs-on: ubuntu-latest
    name: Continuous integration tests
    env:
        working-directory: ./
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Check notebooks
        id: nbdev_test
        #uses: Datahel/analytics_template@main
        uses: ./.github/actions/run-container
        env:
          MODE: ci-test