on: [push]

jobs:
  ci_test_job:
    runs-on: ubuntu-latest
    name: Continuous integration tests
    env:
        working-directory: ./
    steps:
      - name: Check notebooks
        id: nbdev_test
        #uses: Datahel/analytics_template@main
        uses: ./action.yml
        env:
          MODE: ci-test